version: '3'

services:
  moinda-db:
    container_name: moinda-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: moinda
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: moinda
      MYSQL_PASSWORD: moinda
    restart: always
    ports:
      - "3306:3306"
    networks:
      - moinda-local

  moinda-app:
    container_name: moinda-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    restart: always
    depends_on:
      - moinda-db
    networks:
      - moinda-local

networks:
  moinda-local:
    driver: bridge